version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'cypress'
        versions: ['7.x']
      - dependency-name: 'framer-motion'
        versions: ['4.x']
