name: Continuous Integration (PR)

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Report machine parameters
        run: npx cypress info

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    needs: install
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy preview
        run: 'npx vercel --token ${VERCEL_TOKEN} > preview-url.txt'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Define preview URL
        id: define_preview_url
        run: |
          export PREVIEW_URL=$(cat preview-url.txt)
          echo "::set-output name=preview_url::${PREVIEW_URL}"

    outputs:
      preview_url: ${{ steps.define_preview_url.outputs.preview_url }}

  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    needs: deploy
    concurrency:
      group: tests-${{ github.ref }}-${{ matrix.containers }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Integration tests'
        env:
          CYPRESS_BASE_URL: ${{ needs.deploy.outputs.preview_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
          COMMIT_INFO_SHA: ${{ github.sha }}
