name: End-to-end tests (PR)
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build:cra
          start: npm start
          wait-on: http://localhost:3000
        env:
          CYPRESS_CACHE_FOLDER: './node_modules/CypressBinary'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
