name: Continuous Integration (PR)

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    needs: install
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy preview
        run: 'npx vercel --token ${VERCEL_TOKEN}'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
