name: End-to-end tests (Push)

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    strategy:
      # Make sure not to cancel other containers when one test fails, as this
      # will kill Cypress processes leaving the Dashboard hanging.
      # See: https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: App build
        run: npm run build:cra

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npx serve -s build -p 3000
          wait-on: http://localhost:3000
          record: true
          parallel: true
          browser: chrome
          group: 'Integration tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
